Decouple number-of-nodes from number-of-bakers
tqtezos/tezos-k8s pull request #100
Opened 2021-02-04 00:28 UTC by elric1

We now consider --number-of-nodes to be the nodes which do not
include a baker/endorser pair.  It's more natural to consider
that:

    $ mkchain --number-of-bakers 40 --number-of-nodes 5 my_chain

will bring up 40 baker nodes and 5 plain nodes.

This is helpful with pulumi because it has been waiting for zero nodes
to come up and timing out.  With the current code:

    $ mkchain --number-of-bakers 40 my_chain

will bring up 40 bakers and a single node.

2021-02-04 23:10 UTC, harryttd commented
Can you please change docs: https://github.com/tqtezos/tezos-k8s/blob/master/mkchain/README.md for mkchain args

2021-02-06 01:44 UTC, nicolasochem requested changes
ok in principle. Documentation should be updated, and the restriction that `number_of_nodes` should be at least 1 must be lifted, since it should be possible to launch a topology with only baking nodes.

`git grep number_of_nodes` and `git grep number-of-nodes` will give pointers as of which parts should be updated.

2021-02-08 17:49 UTC, elric1 commented
I have made the requested updates.

2021-02-08 18:55 UTC, harryttd commented on mkchain/README.md
> +| number_of_nodes                  | --number-of-nodes  | Number number of plain nodes in the cluster                                 | 1                      |
'number' repeated twice. Also, can you make it something like `Number of non-baker nodes in the cluster`? Might not be clear what 'plain' means.

2021-02-08 20:32 UTC, harryttd commented
Realized another thing: The default number of nodes should now be 1 (and reflected in mkchain docs). It used to be only 1 node was spun up by default and that node was the bootstrap/baker. With these changes, two nodes would be spun up, one peer and one baker. 

I'm working on the top level README.md to reflect all these changes.

2021-02-08 21:45 UTC, harryttd approved these changes

2021-02-08 22:21 UTC, nicolasochem approved these changes

2021-02-08 22:38 UTC, merged