Remove docker as a dependency of mkchain
tqtezos/tezos-k8s pull request #121
Opened 2021-02-24 21:13 UTC by harryttd

2021-02-25 16:44 UTC, elric1 commented
A general comment is: maybe we should have `mkchain` add comments to the values.yaml files to help people understand what they can edit?

2021-02-25 17:10 UTC, harryttd commented
I agree with Roland, but being as many things are changing bec of public nets, I think we should hold off until the values file format gets set in stone.

2021-02-25 18:29 UTC, elric1 commented
I added #122 for the comments, it should be done later.

2021-02-26 20:05 UTC, nicolasochem requested changes
I tried create with both a brand new values file and then overwriting an existing values files with default params and it worked.

I didn't try invite.

I have comment on the output itself.

Running with no parameters yields the result:

```
accounts: []
bootstrap_peers: []
chain_name: niconodocker
genesis:
  timestamp: '2021-02-26T18:41:05.485878+00:00'
images:
  tezos: tezos/tezos:v8-release
is_invitation: false
nodes:
  baking:
  - bake_for: baker0
    bootstrap: true
  regular:
  - {}
rpc_auth: false
zerotier_config:
  zerotier_network: null
  zerotier_token: null
zerotier_in_use: false
```

I feel like this is too much magic. It makes you assume that there are no accounts declared in your chain. but then what is "baker0"?

We should declare all accounts in values.yaml, and let the init container autogenerate an address for it if it's not specified.

Something like:

```
accounts:
  - name: baker0
bootstrap_peers: []
chain_name: niconodocker
genesis:
  timestamp: '2021-02-26T18:41:05.485878+00:00'
images:
  tezos: tezos/tezos:v8-release
is_invitation: false
nodes:
  baking:
  - bake_for: baker0
    bootstrap: true
  regular:
  - {}
rpc_auth: false
zerotier_config:
  zerotier_network: null
  zerotier_token: null
zerotier_in_use: false
```

If `accounts` is completely absent then we can let the magic happen:

```
bootstrap_peers: []
chain_name: niconodocker
genesis:
  timestamp: '2021-02-26T18:41:05.485878+00:00'
images:
  tezos: tezos/tezos:v8-release
is_invitation: false
nodes:
  baking:
  - bake_for: nochem0
    bootstrap: true
  regular:
  - {}
rpc_auth: false
zerotier_config:
  zerotier_network: null
  zerotier_token: null
zerotier_in_use: false
```

The above would generate an account named `nochem0` in the init container. This is a convenience for users that do not use mkchain. But mkchain should be explicit about which accounts it expects to exist.

Also README should be edited to drop docker as a requirement.

2021-06-11 13:51 UTC, elric1 commented
I think that this PR is obsoleted by PR#205 which accomplishes the same thing in a slightly different and more comprehensive way.

2021-06-11 15:29 UTC, harryttd commented
Will be closed by #205

2021-06-11 15:29 UTC, closed without merging