Use the provided image for all tezos binaries
tqtezos/tezos-k8s pull request #177
Opened 2021-03-30 00:00 UTC by elric1

To do this, we switch from making containers based on
tezos/tezos:v8-release to making containers that either:

	1. use the provided tezos image and execute
	   a script which is passed in via the
	   statefulset configuration, or

	2. are not based on the tezos image and do not
	   contain tezos binaries.  These containers
	   prepare configuration, files, etc., for the
	   later containers.

2021-03-31 05:47 UTC, nicolasochem requested changes
This would close https://github.com/tqtezos/tezos-k8s/issues/120 as well.

I tried running mkchain with no parameters and it failed with the following helm error:

```
[venv] nochem@peck ~/workspace/tezos-k8s () $ rm nico_values.yaml 
[venv] nochem@peck ~/workspace/tezos-k8s () $ mkchain nico
Generating vanity chain id
Generating keys for account baker0
Wrote chain creation constants to /home/nochem/workspace/tezos-k8s/nico_values.yaml
[venv] nochem@peck ~/workspace/tezos-k8s () $ helm install --replace nico charts/tezos --values nico_values.yaml --namespace tqtezos --create-namespace
Error: YAML parse error on tezos-chain/templates/baker.yaml: error converting YAML to JSON: yaml: line 22: mapping values are not allowed in this context
```

It's not immediately obvious what is causing this, line 22 looks fine to me.

2021-04-15 16:21 UTC, nicolasochem requested changes
I cannot build utils container due to missing shell script.

2021-04-15 16:21 UTC, nicolasochem commented on utils/Dockerfile
> +COPY config-generator.sh /
Did you forget to check this file in?

2021-04-15 16:25 UTC, elric1 commented on utils/Dockerfile
> +COPY config-generator.sh /
Yes, in fact, I did forget this one.

2021-04-15 17:49 UTC, nicolasochem requested changes
Thanks for this.

I tried:

* mkchain with no parameters: ok
* mkchain with 2 bakers: ok
* boot florence from snapshot failed silently to import snapshot. Chain started syncing from scratch.

It looks like we are missing another file in source control `snapshot-importer.sh`

2021-04-16 02:45 UTC, nicolasochem requested changes
with latest commit, I was able to launch florencenet and have it sync from bootstrap.

But now, I saw that invite is broken.

I created a zerotier chain: `mkchain nico --zerotier-network $ZT_NET --zerotier-token $ZT_TOKEN`

`nico_values.yaml` deployed fine but `nico_invite_values.yaml` gave me this error in the configure step:

```│ + CMD=config-generator                                                                                                                                                                                                                                     │
│ + shift                                                                                                                                                                                                                                                    │
│ + exec /config-generator.sh --generate-config-json                                                                                                                                                                                                         │
│ + ls -l /etc/tezos/data                                                                                                                                                                                                                                    │
│ ls: /etc/tezos/data: No such file or directory                                                                                                                                                                                                             │
│ + echo ------------------------------------------------------------                                                                                                                                                                                        │
│ ------------------------------------------------------------                                                                                                                                                                                               │
│ + cat /etc/tezos/data/config.json                                                                                                                                                                                                                          │
│ cat: can't open '/etc/tezos/data/config.json': No such file or directory                                                                                                                                                                                   │
│ + echo ------------------------------------------------------------                                                                                                                                                                                        │
│ ------------------------------------------------------------                                                                                                                                                                                               │
│ + mkdir -p /var/tezos/client                                                                                                                                                                                                                               │
│ + chmod -R 777 /var/tezos/client                                                                                                                                                                                                                           │
│ + python3 /config-generator.py --generate-config-json                                                                                                                                                                                                      │
│ Importing keys                                                                                                                                                                                                                                             │
│   Importing keys for account: baker0                                                                                                                                                                                                                       │
│     Public key specified                                                                                                                                                                                                                                   │
│     Appending public key: edpkunvwGbaZQx6u1qL6pdGg97BTjBHt9KLV8ysz6hupd8BauKE2DJ                                                                                                                                                                           │
│   Appending public key hash: tz1fymSaKG25y2dsdQGwPcY2uS2isjsNZtST                                                                                                                                                                                          │
│   Account key type: public                                                                                                                                                                                                                                 │
│   Account bootstrap balance: 4000000000000                                                                                                                                                                                                                 │
│   Is account a bootstrap baker: True                                                                                                                                                                                                                       │
│   Writing /var/tezos/client/secret_keys                                                                                                                                                                                                                    │
│   Writing /var/tezos/client/public_keys                                                                                                                                                                                                                    │
│   Writing /var/tezos/client/public_key_hashs                                                                                                                                                                                                               │
│ Starting config.json file generation                                                                                                                                                                                                                       │
│ Traceback (most recent call last):                                                                                                                                                                                                                         │
│   File "/config-generator.py", line 490, in <module>                                                                                                                                                                                                       │
│     main()                                                                                                                                                                                                                                                 │
│   File "/config-generator.py", line 110, in main                                                                                                                                                                                                           │
│     raise Excep [...]

2021-05-03 22:28 UTC, harryttd commented on utils/snapshot-downloader.sh
> +# If we are snapshotting, we download the snapshot here because the snapshot
This comment should be removed because there is no standalone snapshot downloader image. This script is being run via the utils image that has curl.

2021-05-04 16:24 UTC, elric1 commented on utils/snapshot-downloader.sh
> +# If we are snapshotting, we download the snapshot here because the snapshot
I've created Issue #190 to track writing the better documentation that we need. And, I've removed this comment which is misleading.

2021-05-04 16:26 UTC, merged