Name the nodes
tqtezos/tezos-k8s pull request #209
Opened 2021-05-27 20:39 UTC by elric1

2021-06-09 16:52 UTC, nicolasochem requested changes
I merged master with this branch, rebuilt the utils container, did `mkchain` with no parameters, and tried to install it on minikube. I got:

```
[venv] nochem@peck ~/workspace/tezos-k8s () $ helm install nico charts/tezos -f nico_values.yaml --namespace nico --create-namespace
Error: template: tezos-chain/templates/nodes.yaml:10:19: executing "tezos-chain/templates/nodes.yaml" at <$val.instances>: nil pointer evaluating interface {}.instances
```

On master branch, same thing works.

2021-06-21 20:01 UTC, harryttd requested changes
https://github.com/tqtezos/tezos-k8s/blob/378414a58e38aeacb0b380034ea80a62a1b5cd19/mkchain/tqchain/mkchain.py#L18-L21 

NODE_TYPE is not being used anymore except https://github.com/tqtezos/tezos-k8s/blob/378414a58e38aeacb0b380034ea80a62a1b5cd19/mkchain/tqchain/mkchain.py#L284-L285

Not sure what that is supposed to change to. NODE_NAME?

2021-06-23 21:30 UTC, elric1 commented on utils/wait-for-bootstrap.sh
> +	|.key + "." + (.key|sub("-[\\d]+$"; ""))'
I've put some comments in and refactored and renamed a little. The function name originally did not help understand what was going on because it was, well, wrong. The new name along with the refactoring and comments should make it a lot more clear.

2021-06-23 21:34 UTC, elric1 commented on utils/logger.sh
> +	i=$(expr $i + 1)
I've added comments and changed some of the variable names which are the worst. `i` is just a loop iterator, this is pretty standard in code, so I think that one is mostly self-explanatory. But, I've fixed up and commented things a lot more, so that, e.g., you know what the point of the function actually is before you read it---this, I expect, will help quite a bit.

2021-06-23 21:36 UTC, elric1 commented on utils/config-generator.py
>      MY_NODE = NODES[MY_NODE_TYPE][MY_POD_NAME]
Hmmmm, I'm not actually using these variables which is why this typo didn't seem to break anything.

2021-06-23 21:39 UTC, elric1 commented on charts/tezos/templates/nodes.yaml
> +{{- include "tezos.container.zerotier"  $ | indent 8 }}
Yeah, I put them here because of . vs $. I can try to move them, I think that we'll get less git conflicts on rebases if I put the conditionals into `_containers.tpl`.

2021-06-23 21:44 UTC, elric1 commented on utils/logger.sh
> +	echo "$BLOCKS" | sed 's/^.* \([^ ]* [^ ]*\)/\1/'
Just truncating to two blocks. Or to put it in regex, chopping off the start of the string up to and including the second to last space character.

2021-06-23 21:46 UTC, elric1 commented on utils/logger.sh
> +	echo "$BLOCKS" | sed 's/^.* \([^ ]* [^ ]*\)/\1/'
I could write it more simply as:
```
    echo "$BLOCKS" | sed -E 's/.* ([^ ]* )/\1/'
```
I think.

2021-06-24 16:48 UTC, elric1 commented on utils/config-generator.py
>      MY_NODE = NODES[MY_NODE_TYPE][MY_POD_NAME]
I pushed a commit that removes a lot of these. The concept of a node type presenting a dichotomy between bakers and nodes is obviated by the list of containers that are run. This information is now encoded by searching for a baker in said list.

2021-06-24 17:47 UTC, elric1 commented on utils/logger.sh
> +	echo "$BLOCKS" | sed 's/^.* \([^ ]* [^ ]*\)/\1/'
I've simplified the expression as above. I think that this makes it easier to read?

2021-07-02 18:24 UTC, harryttd commented on utils/config-generator.py
> +            pubkey_and_balance_pairs.append([v["pk"], v["bootstrap_balance"]])
I think this might be lacking some of the currently existing logic.

To be part of parameters.json, not only does the `bootstrap_balance` property need to exist on the account, it needs to have tez. So the value has to be greater than 0.

Also, there is a discrepancy in the type of key used which depends upon if the account is a bootstrap baker account or a regular non-baking bootstrap account. A baker account gets its pubkey added to parameters.json, while a regular account gets its pubkey hash added to parameters.json.

2021-07-08 22:34 UTC, elric1 commented
I've rebased, cleaned up, squashed some, re-ordered others, etc and I'm going to start the review again in a new PR.

2021-07-08 22:34 UTC, closed without merging

2021-08-04 17:39 UTC, elric1 commented
This also addressed issue #158?

2021-08-04 18:10 UTC, harryttd commented
@elric1 Yup it looks like this PR covered that. Please link it to this PR and close it when you can