Allow for multiple baking accounts per baker
tqtezos/tezos-k8s pull request #231
Opened 2021-07-20 21:31 UTC by elric1

As requested in Issue #214, we implement multiple baker accounts per
baker.  We update the definition of instances in the node section
to allow:

  tezos-baking-node:
    runs:
    - baker
    - endorser
    storage_size: 15Gi
    instances:
    - bake_using_accounts:
      - baker0.0
      - baker0.1
      - baker0.2
      config:
        shell:
          history_mode: full
      is_bootstrap_node: true

If "bake_using_accounts" is provided, then it is interpreted as a list
of accounts.  The will be automatically created if they don't exist when
"should_generate_unsafe_deterministic_data" is true.

"bake_using_account" is still honoured.  It is an error to specify both.

mkchain still makes parameters files using "bake_using_account" so that
we can use a newer mkchain with slightly older charts.  We expect to
deprecate this and update in the future.

2021-07-20 22:54 UTC, nicolasochem approved these changes
Thank you. It works: I did `mkchain --number-of-bakers 2` then deleted the second node and configured the first one with `bake_using_accounts` and the baker came up, baked for both accounts and used the remote signer correctly.

I tried a few more things just for fun:

* same than above, but with 2 remote signers
* one account using a remote signer and one local

It worked.

2021-07-21 20:17 UTC, elric1 commented
I just finished the `verify_this_bakers_account()` logic and did a quick force push.

2021-07-21 21:14 UTC, nicolasochem requested changes
I think you broke non-baking nodes?

This is what I get in the regular nodes after `mkchain --number-of-bakers 2 --number-of-nodes 1`:

```
│ + CMD=config-generator                                                                                                                                                                                                                                     │
│ + shift                                                                                                                                                                                                                                                    │
│ + exec /config-generator.sh --generate-config-json                                                                                                                                                                                                         │
│ + ls -l /etc/tezos/data                                                                                                                                                                                                                                    │
│ ls: /etc/tezos/data: No such file or directory                                                                                                                                                                                                             │
│ ------------------------------------------------------------                                                                                                                                                                                               │
│ + echo ------------------------------------------------------------                                                                                                                                                                                        │
│ + cat /etc/tezos/data/config.json                                                                                                                                                                                                                          │
│ cat: can't open '/etc/tezos/data/config.json': No such file or directory                                                                                                                                                                                   │
│ + echo ------------------------------------------------------------                                                                                                                                                                                        │
│ + mkdir -p /var/tezos/client                                                                                                                                                                                                                               │
│ ------------------------------------------------------------                                                                                                                                                                                               │
│ + chmod -R 777 /var/tezos                                                                                                                                                                                                                                  │
│ + set -e                                                                                                                                                                                                                                                   │
│ + python3 /config-generator.py --generate-config-json                                                                                                                                                                                                      │
│ Importing keys                                                                                                                                                                                                                                             │
│   Importing keys for account: tezos-baking-node-0                                                                                                                                                                                                          │
│ Traceback (most recent call last):                                                                                                                                                                                                                         │
│   File "/config-generator.py", line 541, in <module>                                                                                                                                                                                                       │
│     main()                                                                                                                                                                                                                                                 │
│   File "/config-generator.py", line 60, in main                                                                                                                                                                                                            │
│     import_keys(all_accounts)                                                                                                                                                                                                                              │
│   File "/config-generator.py", line 340, in import_keys                                                                                                                                                                                                    │
│     if expose_secret_key(account_name):                                                                                                                                                                                                                    │
│   File "/config-generator.py", line 281, in expose_secret_key                                                                                                                                                                                              │
│     return account_name in MY_POD_CONFIG.get("bake_using_accounts")                                                                                                                                                                                        │
│ TypeError: argument of type 'NoneType' is not iterable                                                                                                                                                                                                     │
│ stream closed                                                                                                                                                                                                                                              │
│                                                                                                                                                                                                                                                            │
│                                                                                                                                                                                                                                                            │
│                        
```

2021-07-21 21:47 UTC, nicolasochem approved these changes
It works again. Thanks!

I won't test zerotier, I don't anticipate any breakage there.

2021-07-21 21:52 UTC, elric1 commented
I squashed them manually to avoid adding "fixup to 4dfcea9" to the commit. They're the same, though:
```
: arioch; git push -f chapeltech multiple-baker-accounts
Enumerating objects: 15, done.
Counting objects: 100% (15/15), done.
Delta compression using up to 2 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 1.70 KiB | 1.71 MiB/s, done.
Total 8 (delta 7), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (7/7), completed with 7 local objects.
To github.com:chapeltech/tezos-k8s
 + 4dfcea9...919196e multiple-baker-accounts -> multiple-baker-accounts (forced
update)
: arioch; git diff  4dfcea9 919196e
: arioch;
```

2021-07-22 05:49 UTC, harryttd approved these changes
I left one little comment. Otherwise code looks good.

2021-07-22 05:49 UTC, harryttd commented on utils/config-generator.py
> +            raise Exception(f"ERROR: Either a secret key was not provided for {acct}")
Is there supposed to be more to this sentence? From the "either" it would seem so.

2021-07-22 06:01 UTC, harryttd commented on utils/config-generator.py
> +        return account_name in MY_POD_CONFIG.get("bake_using_accounts", {})
What if the non plural accounts was specified in the config of the node? If baker accounts are not filled in then the plural list is not added to the nodes config. So this check would return false in the case of singular account specified. 

Forgive me if this makes no sense. I'm reviewing from my phone and did not test.

2021-07-22 13:02 UTC, elric1 commented on utils/config-generator.py
> +        return account_name in MY_POD_CONFIG.get("bake_using_accounts", {})
The was fixed up earlier---but not in every code branch. I've fixed it, rebased onto master, squashed, and force pushed.

2021-07-26 20:24 UTC, elric1 commented
I rebased in my local git repo. The commit "Provide default value for activation account" was mistakenly pushed and I've taken it out---it belongs in another pull request.

2021-07-26 20:24 UTC, merged