Update helm chart ref and change tqtezos to oa
tqtezos/tezos-k8s pull request #239
Opened 2021-08-02 19:09 UTC by orcutt989

2021-08-03 01:53 UTC, harryttd commented
Looks great. Do you mind also updating a few spots in DEVELOPMENT.md?

2021-08-03 05:01 UTC, orcutt989 commented
> Looks great. Do you mind also updating a few spots in DEVELOPMENT.md?

Woops - absolutely! Done

2021-08-04 15:28 UTC, harryttd requested changes

2021-08-04 15:28 UTC, harryttd commented on rpc-auth/README.md
> -- [tezos-client](https://assets.tqtezos.com/docs/setup/1-tezos-client/)
I know it's confusing. This is a place that shouldn't get changed to oxheadalpha. This site is still owned by tqtezos

2021-08-04 15:48 UTC, orcutt989 commented
> Just wanted to leave a comment that I think the docker username and password will need to change as they are currently for the TQ account.
> 
> 
> 
> PyPi shouldn't have to change I think bec it is an account not tied to TQ.

Yep thanks for the note. I have an issue for this already I think

2021-08-04 16:22 UTC, harryttd commented
Looks good! Can you please squash and merge this?
Thank you!

2021-08-04 16:22 UTC, harryttd approved these changes

2021-08-04 17:13 UTC, nicolasochem approved these changes

2021-08-04 17:16 UTC, merged