Only import the required keys in init containers
tqtezos/tezos-k8s pull request #80
Opened 2021-01-25 22:26 UTC by elric1

We can improve this further in time for large scale nodes, specifically, maybe we can just create one bootstrap account on a single node and have bakers create their own accounts as they spawn and then drink from a faucet. This would scale much better as we wouldn't have to create all of the accounts serially in advance but would rather create them in parallel at spawn time.

2021-01-26 01:11 UTC, nicolasochem commented on key-importer/entrypoint.sh
> +set -x
this prints the secret keys in the init container log, please remove.

2021-01-26 10:59 UTC, elric1 commented on key-importer/entrypoint.sh
> +set -x
Okay, I've update this. I also put logic in to not double import baker0's key.

2021-01-26 16:29 UTC, nicolasochem approved these changes

2021-01-26 16:45 UTC, nicolasochem requested changes
actually just realized it breaks the multiple baker use case

2021-01-26 21:34 UTC, elric1 commented
The issue was that the keys were not imported into the activate-job. I've fixed that.

2021-01-26 22:37 UTC, harryttd commented
Only baker0 is baking for me. But the parameters.json seems the same. the only diff is that each node has diff bootstrap_accounts which makes sense

2021-01-26 23:10 UTC, elric1 commented
Hmmm, all of my bakers appear to be "Injecting block"s.

2021-01-26 23:12 UTC, harryttd commented
do they say "no slot found at level..." compared to baker-0?

2021-01-27 22:00 UTC, nicolasochem approved these changes
It works now after rebase, so I suppose it didn't have all the changes in master.

In the process we realized that the nodes don't need parameters.json (only activate does) so it should be removed.

2021-01-28 11:31 UTC, merged