wait-for-bootstrap: use either node-0 or node-1 to help with deadlocks.
tqtezos/tezos-k8s pull request #99
Opened 2021-02-04 00:26 UTC by elric1

2021-02-04 18:28 UTC, harryttd commented on wait-for-bootstrap/entrypoint.sh
> +	if </dev/null nc -q 0 ${node} 8732; then
can we log on success that we have connected and to which node?

2021-02-06 02:49 UTC, nicolasochem requested changes
It makes sense, but do not assume tezos-baking-node-0 and tezos-baking-node-1 are bootstrap. We define bootstrap nodes in helm values. For example, mkchain gives me:

```
nodes:
  baking:
  - bake_for: baker0
    bootstrap: true
  - bake_for: baker1
    bootstrap: true
  - bake_for: baker2
```

But anyone could launch a topology such as:

```
nodes:
  baking:
  - bake_for: baker0
  - bake_for: baker1
    bootstrap: true
  - bake_for: baker2
    bootstrap: true
```

In which case `BOOTSTRAP_NODE="tezos-baking-node-1.tezos-baking-node tezos-baking-node-2.tezos-baking-node"`

So BOOTSTRAP_NODES list has to be built generically; I recommend passing the `nodes` helm value as json and using jq to generate it.

See how it is done in config-generator:

https://github.com/tqtezos/tezos-k8s/blob/master/config-generator/entrypoint.py#L47-L54

2021-03-10 00:26 UTC, elric1 commented on wait-for-bootstrap/entrypoint.sh
> +	if </dev/null nc -q 0 ${node} 8732; then
I made it a lot more chatty.

2021-03-10 00:28 UTC, elric1 commented
I've updated this to grab the bootstrap nodes from `CHAIN_PARAMS` as suggested. I force pushed as it's essentially a new attempt. I also included a couple of commits for small issues that I noticed along the way.

2021-03-24 12:07 UTC, elric1 commented
So, after the structural changes to values files just merged in, I've restructured this to use `$NODES` rather than `$CHAIN_NAME`. It's still filtering for the configured bootstrap hosts without making assumptions.

2021-03-24 15:08 UTC, elric1 commented
I've made this address #161 as a drive-by.

2021-03-24 15:58 UTC, elric1 commented
Make new PR.

2021-03-24 15:58 UTC, closed without merging